//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppWorks.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppWorks.UI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit.
        /// </summary>
        public static string btnEdit {
            get {
                return ResourceManager.GetString("btnEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string BtnLogin {
            get {
                return ResourceManager.GetString("BtnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string btnSave {
            get {
                return ResourceManager.GetString("btnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string btnUpdate {
            get {
                return ResourceManager.GetString("btnUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lengh of credential (max 20 and min 4) violates !.
        /// </summary>
        public static string ErrorCredentialLenght {
            get {
                return ResourceManager.GetString("ErrorCredentialLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error encountered while editing the damage code.
        /// </summary>
        public static string ErrorDamageCode {
            get {
                return ResourceManager.GetString("ErrorDamageCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not Insert Duplicate Code and CodeType.
        /// </summary>
        public static string ErrorDuplicateCode {
            get {
                return ResourceManager.GetString("ErrorDuplicateCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a Valid email Address..
        /// </summary>
        public static string ErrorEmail {
            get {
                return ResourceManager.GetString("ErrorEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a valid PIN..
        /// </summary>
        public static string ErrorEmptyPin {
            get {
                return ResourceManager.GetString("ErrorEmptyPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a valid Usercode..
        /// </summary>
        public static string ErrorEmptyUserCode {
            get {
                return ResourceManager.GetString("ErrorEmptyUserCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Code!.
        /// </summary>
        public static string ErrorEnterCode {
            get {
                return ResourceManager.GetString("ErrorEnterCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Insertion Error..
        /// </summary>
        public static string ErrorInserted {
            get {
                return ResourceManager.GetString("ErrorInserted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The User Name that was entered has no roles assigned to it, contact the System Administrator!.
        /// </summary>
        public static string ErrorNoRoleAsign {
            get {
                return ResourceManager.GetString("ErrorNoRoleAsign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password cannot be blank !.
        /// </summary>
        public static string ErrorPasswordText {
            get {
                return ResourceManager.GetString("ErrorPasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to Update!.
        /// </summary>
        public static string ErrorToUpdate {
            get {
                return ResourceManager.GetString("ErrorToUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usercode already exists !.
        /// </summary>
        public static string ErrorUserCode {
            get {
                return ResourceManager.GetString("ErrorUserCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username and Pasword cannot be blank !.
        /// </summary>
        public static string ErrorUsernameAndPasswordText {
            get {
                return ResourceManager.GetString("ErrorUsernameAndPasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username cannot be blank !.
        /// </summary>
        public static string ErrorUsernameText {
            get {
                return ResourceManager.GetString("ErrorUsernameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or Password is Wrong !.
        /// </summary>
        public static string ErrorWrongCredential {
            get {
                return ResourceManager.GetString("ErrorWrongCredential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inbound inspection.
        /// </summary>
        public static string InspectionType1 {
            get {
                return ResourceManager.GetString("InspectionType1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to outbound inspection.
        /// </summary>
        public static string InspectionType2 {
            get {
                return ResourceManager.GetString("InspectionType2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yard inspection.
        /// </summary>
        public static string InspectionType3 {
            get {
                return ResourceManager.GetString("InspectionType3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string lblPassword {
            get {
                return ResourceManager.GetString("lblPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string lblUserName {
            get {
                return ResourceManager.GetString("lblUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End {2} function ::{0} {1}..
        /// </summary>
        public static string loggerMsgEnd {
            get {
                return ResourceManager.GetString("loggerMsgEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Called {2} function ::{0} {1}..
        /// </summary>
        public static string loggerMsgStart {
            get {
                return ResourceManager.GetString("loggerMsgStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string MsgAll {
            get {
                return ResourceManager.GetString("MsgAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select a Batch to Continue..
        /// </summary>
        public static string msgBatchReq {
            get {
                return ResourceManager.GetString("msgBatchReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error creating the main billing line item..
        /// </summary>
        public static string msgBillingError {
            get {
                return ResourceManager.GetString("msgBillingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error inserting the Billing Line Items record..
        /// </summary>
        public static string msgBillingLineError {
            get {
                return ResourceManager.GetString("msgBillingLineError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Calender Year and Period Number that you entered already exists,you must enter unique combination of calender year and Period Number.
        /// </summary>
        public static string msgCalanderYearPerodNumberAlredy {
            get {
                return ResourceManager.GetString("msgCalanderYearPerodNumberAlredy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter calander year..
        /// </summary>
        public static string msgCalanderYearReq {
            get {
                return ResourceManager.GetString("msgCalanderYearReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Billing Address.
        /// </summary>
        public static string msgChangeBillAddressTitleBox {
            get {
                return ResourceManager.GetString("msgChangeBillAddressTitleBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to change the Billing Address?.
        /// </summary>
        public static string msgChangeBillingAddConfirm {
            get {
                return ResourceManager.GetString("msgChangeBillingAddConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to change the Street Address?.
        /// </summary>
        public static string msgChangeStreetAddConfirm {
            get {
                return ResourceManager.GetString("msgChangeStreetAddConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Code is Already Exist!.
        /// </summary>
        public static string msgCodeAlready {
            get {
                return ResourceManager.GetString("msgCodeAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Customer Code.
        /// </summary>
        public static string msgCustomerCodeReq {
            get {
                return ResourceManager.GetString("msgCustomerCodeReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Customer Name.
        /// </summary>
        public static string msgCustomerNameReq {
            get {
                return ResourceManager.GetString("msgCustomerNameReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Customer Type.
        /// </summary>
        public static string msgCustomerTypeReq {
            get {
                return ResourceManager.GetString("msgCustomerTypeReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage codes must contain 5 numbers.
        /// </summary>
        public static string msgDamageCodeNumberValidation {
            get {
                return ResourceManager.GetString("msgDamageCodeNumberValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter atleast one damage code.
        /// </summary>
        public static string msgDamageCodeReq {
            get {
                return ResourceManager.GetString("msgDamageCodeReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage codes can only contain numbers.
        /// </summary>
        public static string msgDamageCodeValidation {
            get {
                return ResourceManager.GetString("msgDamageCodeValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date can not be Greater than End Date..
        /// </summary>
        public static string msgDateCompair {
            get {
                return ResourceManager.GetString("msgDateCompair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed Record(s) Found :\n Cust:.
        /// </summary>
        public static string msgDateoutProcess {
            get {
                return ResourceManager.GetString("msgDateoutProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date/End Date can not be blank..
        /// </summary>
        public static string msgDateReq {
            get {
                return ResourceManager.GetString("msgDateReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error creating the dealer storage line item..
        /// </summary>
        public static string msgDealerError {
            get {
                return ResourceManager.GetString("msgDealerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete?.
        /// </summary>
        public static string MsgDeleteConfirm {
            get {
                return ResourceManager.GetString("MsgDeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Deleted Successfully..
        /// </summary>
        public static string msgDeleteSuccessfully {
            get {
                return ResourceManager.GetString("msgDeleteSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter an End Date..
        /// </summary>
        public static string msgEndDateReq {
            get {
                return ResourceManager.GetString("msgEndDateReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter an ending Invoice Number..
        /// </summary>
        public static string msgEndInvoiceReq {
            get {
                return ResourceManager.GetString("msgEndInvoiceReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to error.
        /// </summary>
        public static string msgError {
            get {
                return ResourceManager.GetString("msgError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Message.
        /// </summary>
        public static string msgErrorMessage {
            get {
                return ResourceManager.GetString("msgErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Find a Billing Period to  Modify!.
        /// </summary>
        public static string MsgFindBillingPeriod {
            get {
                return ResourceManager.GetString("MsgFindBillingPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Find a Customer to Modify!.
        /// </summary>
        public static string MsgFindCustomer {
            get {
                return ResourceManager.GetString("MsgFindCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error looking up the Accounts Receivable Control GL Account Number. Please check the Codes table to ensure that the value exists!.
        /// </summary>
        public static string msgGenrateInvoiceAccountReceivable {
            get {
                return ResourceManager.GetString("msgGenrateInvoiceAccountReceivable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error looking up the Boston Autoport Stoarge GL Account Number. Please check the Codes table to ensure that the value exists!.
        /// </summary>
        public static string msgGenrateInvoiceBostonAutoport {
            get {
                return ResourceManager.GetString("msgGenrateInvoiceBostonAutoport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error looking up the Credit Cost Center Number. Please check the Codes table to ensure that the value exists!.
        /// </summary>
        public static string msgGenrateInvoiceCostCenter {
            get {
                return ResourceManager.GetString("msgGenrateInvoiceCostCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error looking up the Credit Cost Center Number. Please check the Codes and Salesperson tables to ensure that the value exists!.
        /// </summary>
        public static string msgGenrateInvoiceCostCenterSales {
            get {
                return ResourceManager.GetString("msgGenrateInvoiceCostCenterSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error determining whether or not the invoice contains a Diversifed and Outside Carrier split. The invoice line items have not been created!.
        /// </summary>
        public static string msgGenrateInvoiceDetermining {
            get {
                return ResourceManager.GetString("msgGenrateInvoiceDetermining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error getting the invoice number length, the invoice has not been created.
        /// </summary>
        public static string msgGenrateInvoiceLength {
            get {
                return ResourceManager.GetString("msgGenrateInvoiceLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error getting invoice number prefix, the invoice has not been created.
        /// </summary>
        public static string msgGenrateInvoicePrefix {
            get {
                return ResourceManager.GetString("msgGenrateInvoicePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error getting the next invoice number, the invoice has not been created!.
        /// </summary>
        public static string msgGenrateInvoicePrefixNext {
            get {
                return ResourceManager.GetString("msgGenrateInvoicePrefixNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error looking up the Profit Center Number. Please check the Codes table to ensure that the value exists!.
        /// </summary>
        public static string msgGenrateInvoiceProfitCenter {
            get {
                return ResourceManager.GetString("msgGenrateInvoiceProfitCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden.
        /// </summary>
        public static string MsgHidden {
            get {
                return ResourceManager.GetString("MsgHidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Inserted Successfully!.
        /// </summary>
        public static string msgInsertedCustomer {
            get {
                return ResourceManager.GetString("msgInsertedCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Inserted Successfully.
        /// </summary>
        public static string msgInsertedSuccessfully {
            get {
                return ResourceManager.GetString("msgInsertedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter an Inspection Date.
        /// </summary>
        public static string msgInspectionDateReq {
            get {
                return ResourceManager.GetString("msgInspectionDateReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select atleast one Inspection Type.
        /// </summary>
        public static string msgInspectionTypeReq {
            get {
                return ResourceManager.GetString("msgInspectionTypeReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the Location Name.
        /// </summary>
        public static string msgLocationNameReq {
            get {
                return ResourceManager.GetString("msgLocationNameReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the Location Sub Type.
        /// </summary>
        public static string msgLocationSubTypeReq {
            get {
                return ResourceManager.GetString("msgLocationSubTypeReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the Location Type.
        /// </summary>
        public static string msgLocationTypeReq {
            get {
                return ResourceManager.GetString("msgLocationTypeReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the Zip Code.
        /// </summary>
        public static string msgLocationZipReq {
            get {
                return ResourceManager.GetString("msgLocationZipReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are multiple open matches for the VIN that you entered!Please use the find window to find these records and make the correct adjustments..
        /// </summary>
        public static string msgMultipleVINProcessing {
            get {
                return ResourceManager.GetString("msgMultipleVINProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New user has been added.
        /// </summary>
        public static string msgNewUserAdded {
            get {
                return ResourceManager.GetString("msgNewUserAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO.
        /// </summary>
        public static string msgNo {
            get {
                return ResourceManager.GetString("msgNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Period Number!.
        /// </summary>
        public static string msgPeriodNumberReq {
            get {
                return ResourceManager.GetString("msgPeriodNumberReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The VIN that you entered was not found in the Port Storage Vehicle table..
        /// </summary>
        public static string msgProcessingVINFound {
            get {
                return ResourceManager.GetString("msgProcessingVINFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Deleted !.
        /// </summary>
        public static string MsgRecordDeleted {
            get {
                return ResourceManager.GetString("MsgRecordDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record updated !.
        /// </summary>
        public static string MsgRecordUpdated {
            get {
                return ResourceManager.GetString("MsgRecordUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select CodeType!.
        /// </summary>
        public static string MsgSelectCodeType {
            get {
                return ResourceManager.GetString("MsgSelectCodeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plese select an User to Continue!.
        /// </summary>
        public static string MsgSelectUser {
            get {
                return ResourceManager.GetString("MsgSelectUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a Start Date..
        /// </summary>
        public static string msgStratDateReq {
            get {
                return ResourceManager.GetString("msgStratDateReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a starting Invoice Number..
        /// </summary>
        public static string msgStratInvoiceReq {
            get {
                return ResourceManager.GetString("msgStratInvoiceReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Box.
        /// </summary>
        public static string msgTitleMessageBox {
            get {
                return ResourceManager.GetString("msgTitleMessageBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Confirmation.
        /// </summary>
        public static string msgTitleMessageBoxDelete {
            get {
                return ResourceManager.GetString("msgTitleMessageBoxDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple Matchches On VIN.
        /// </summary>
        public static string msgTitleMessageBoxMultipleVIN {
            get {
                return ResourceManager.GetString("msgTitleMessageBoxMultipleVIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Already In List.
        /// </summary>
        public static string msgTitleMessageBoxVehicleList {
            get {
                return ResourceManager.GetString("msgTitleMessageBoxVehicleList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Not Found.
        /// </summary>
        public static string msgTitleMessageBoxVehicleNotFound {
            get {
                return ResourceManager.GetString("msgTitleMessageBoxVehicleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Number of Units:.
        /// </summary>
        public static string msgTotalUnitReport {
            get {
                return ResourceManager.GetString("msgTotalUnitReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to Update Common Location!.
        /// </summary>
        public static string msgUpdateCommonLocation {
            get {
                return ResourceManager.GetString("msgUpdateCommonLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Updated Successfully..
        /// </summary>
        public static string msgUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("msgUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is last most record..
        /// </summary>
        public static string msgVehicleLastRecord {
            get {
                return ResourceManager.GetString("msgVehicleLastRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already added this vehicle to the list..
        /// </summary>
        public static string msgVehicleListAlready {
            get {
                return ResourceManager.GetString("msgVehicleListAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is previous most record..
        /// </summary>
        public static string msgVehiclePrevRecord {
            get {
                return ResourceManager.GetString("msgVehiclePrevRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to view.
        /// </summary>
        public static string msgview {
            get {
                return ResourceManager.GetString("msgview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter VIN Number and Customer Detail.
        /// </summary>
        public static string msgVINCustomerReq {
            get {
                return ResourceManager.GetString("msgVINCustomerReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a VIN.
        /// </summary>
        public static string msgVINReq {
            get {
                return ResourceManager.GetString("msgVINReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visible.
        /// </summary>
        public static string MsgVisible {
            get {
                return ResourceManager.GetString("MsgVisible", resourceCulture);
            }
        }
    }
}
